openapi: 3.0.0
info:
  title: Booklet API
  version: 1.0.0
paths:
  /api/books:
    get:
      summary: Get a list of books
      description: Returns a list of books, optionally filtered by query param 'q'
      parameters:
        - name: q
          in: query
          description: Query string to filter books by title
          schema:
            type: string
            minLength: 3
      responses:
        200:
          description: A list of books
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    author:
                      type: string
                    publication_year:
                      type: integer
                    genre:
                      type: array
                      items:
                        type: string
                    description:
                      type: string
                    cover_image:
                      type: string
                      format: uri
        404:
          description: No books found
        422:
          description: Invalid query parameter
  /api/book/{bookId}/checkout:
    post:
      summary: Checkout a book
      description: Checkout a book by ID
      parameters:
        - name: bookId
          in: path
          description: ID of the book to checkout
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Book checked out successfully
